version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: powercast_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: powercast
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: powercast
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
